Bind("SUPER + e", "rofi -show drun")
Bind("SUPER + d", "rofi -show run")
Bind("SUPER + x", "rofi -show ssh")
Bind("SUPER + period", "rofimoji --action copy --selector-args='-theme grid-picker.rasi'")
Bind("SUPER + comma", "~/.scripts/rofiGlyphs")
Bind("SUPER + c", "rofi -show calc")
Bind("SUPER + v", "clipmenu")

Bind("SUPER + t", TERMINAL)
Bind("SUPER + w", WEB_BROWSER)
Bind("SUPER + SHIFT + w", WEB_BROWSER .. "--target window https://web.whatsapp.com")
Bind("SUPER + SHIFT + f", GUI_FILE_MANAGER)
Bind("SUPER + b", LAUNCH_IN_TERM .. "bluetuith", { float = true })
Bind("SUPER + p", LAUNCH_IN_TERM .. "pulsemixer", { float = true })
Bind("SUPER + r", LAUNCH_IN_TERM .. "ranger", { float = true })
Bind("SUPER + n", LAUNCH_IN_TERM .. "nvim", { float = true })
Bind("SUPER + o", LAUNCH_IN_TERM .. "calcurse", { float = true })
Bind("SUPER + ALT + u", LAUNCH_IN_TERM .. "paru -Syu")
Bind("SUPER + SHIFT + m", LAUNCH_IN_TERM .. "neomutt")
Bind("SUPER + SHIFT + b", LAUNCH_IN_TERM .. "btop")
Bind("SUPER + SHIFT + n", LAUNCH_IN_TERM .. "notes")
Bind("SUPER + SHIFT + t", LAUNCH_IN_TERM .. "conf")
Bind("SUPER + SHIFT + g", LAUNCH_IN_TERM .. "~/.scripts/record")

Bind("SUPER + SHIFT + p", "spotify-launcher", { workspace = 9 })

Bind("SUPER + SHIFT + c", "~/.scripts/screenshot")
Bind("SUPER + SHIFT + o", "~/.scripts/set-default-output-source")
Bind("SUPER + SHIFT + i", "~/.scripts/set-default-input-source")

Bind("SUPER + SHIFT + z", "~/.scripts/get-window-class")
Bind("SUPER + SHIFT + x", "hyprpicker -a")
Bind("SUPER + SHIFT + d", "rofi-pass")
