UP add volume +2
DOWN add volume -2
WHEEL_UP add volume +2
WHEEL_DOWN add volume -2

: script-binding commands/open

H  seek -5
L  seek +5

h  seek -10
l  seek +10

Ctrl+h  seek -50
Ctrl+l  seek +50

j add volume -5
k add volume 5

Ctrl+j Down


Ctrl+y script-binding quality_menu/video_formats_toggle
Ctrl+Y script-binding quality_menu/audio_formats_toggle
