-- hyprland.lua
-- Generated by hypr-migrate from: mocha.conf
-- Hyprland >= 0.55 required — https://wiki.hypr.land/
--
-- MIGRATION SUMMARY:
--   Variables:       52 resolved
--   Config keys:     0 emitted
--   Monitors:        0
--   Keybinds:        0 total, 0 collapsed into loops
--   Window rules:    0 total, 0 merged
--   Workspace rules: 0
--   Exec commands:   0
--   Gestures:        0
--   Warnings:        0  ← search MIGRATION_WARNING
--   Review needed:   0  ← search MIGRATION_NOTE
--
-- IMPORTANT: Verify output against https://wiki.hypr.land/ before use
-- The wiki is the only authoritative reference for Lua syntax.

local rosewater = "rgba(f5e0dcff)"
local rosewaterAlpha = "f5e0dc"
local flamingo = "rgba(f2cdcdff)"
local flamingoAlpha = "f2cdcd"
local pink = "rgba(f5c2e7ff)"
local pinkAlpha = "f5c2e7"
local mauve = "rgba(cba6f7ff)"
local mauveAlpha = "cba6f7"
local red = "rgba(f38ba8ff)"
local redAlpha = "f38ba8"
local maroon = "rgba(eba0acff)"
local maroonAlpha = "eba0ac"
local peach = "rgba(fab387ff)"
local peachAlpha = "fab387"
local yellow = "rgba(f9e2afff)"
local yellowAlpha = "f9e2af"
local green = "rgba(a6e3a1ff)"
local greenAlpha = "a6e3a1"
local teal = "rgba(94e2d5ff)"
local tealAlpha = "94e2d5"
local sky = "rgba(89dcebff)"
local skyAlpha = "89dceb"
local sapphire = "rgba(74c7ecff)"
local sapphireAlpha = "74c7ec"
local blue = "rgba(89b4faff)"
local blueAlpha = "89b4fa"
local lavender = "rgba(b4befeff)"
local lavenderAlpha = "b4befe"
local text = "rgba(cdd6f4ff)"
local textAlpha = "cdd6f4"
local subtext1 = "rgba(bac2deff)"
local subtext1Alpha = "bac2de"
local subtext0 = "rgba(a6adc8ff)"
local subtext0Alpha = "a6adc8"
local overlay2 = "rgba(9399b2ff)"
local overlay2Alpha = "9399b2"
local overlay1 = "rgba(7f849cff)"
local overlay1Alpha = "7f849c"
local overlay0 = "rgba(6c7086ff)"
local overlay0Alpha = "6c7086"
local surface2 = "rgba(585b70ff)"
local surface2Alpha = "585b70"
local surface1 = "rgba(45475aff)"
local surface1Alpha = "45475a"
local surface0 = "rgba(313244ff)"
local surface0Alpha = 313244
local base = "rgba(1e1e2eff)"
local baseAlpha = "1e1e2e"
local mantle = "rgba(181825ff)"
local mantleAlpha = 181825
local crust = "rgba(11111bff)"
local crustAlpha = "11111b"
