hl.on("hyprland.start", function()
	hl.exec_cmd("hyprctl setcursor catppuccin-mocha-blue 16")
	hl.exec_cmd("waybar")
	hl.exec_cmd(
		"bash -c 'playerctl metadata --player=spotify --follow | while read -r _; do pkill -RTMIN+10 waybar; done &'"
	)
	hl.exec_cmd("qutebrowser", { workspace = 1 })
	hl.exec_cmd("~/.scripts/discord-startup-handler")
	hl.exec_cmd("spotify-launcher")
	hl.exec_cmd("hyprsunset")
	hl.exec_cmd("systemctl --user start hyprpolkitagent")
	hl.exec_cmd("dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
	hl.exec_cmd("dbus-update-activation-environment --systemd --all")
	hl.exec_cmd("systemctl --user import-environment QT_QPA_PLATFORMTHEME")
	hl.exec_cmd("hyprpaper")
	hl.exec_cmd("swayosd-server")
	hl.exec_cmd("discover-overlay")
	hl.exec_cmd("darkman run")
	hl.exec_cmd("udiskie")
end)
