# If you want to negate a ReGex, as in pass only when the RegEx fails, you can prefix it with negative:, e.g.: negative:kitty.

windowrule {
  name = tile_mc
  match:class = Minecraft.*
  float = off
}

# Ignore maximize requests from apps. You'll probably like this.
windowrule {
  name = windowrule-1
  match:class = .*
  suppress_event = maximize
}

# Fix some dragging issues with XWayland
windowrule {
  name = XWayland

  match:class = ^$
  match:title = ^$
  match:xwayland = 1
  match:fullscreen = 0
  match:float = 1
  match:pin = 0

  no_initial_focus = 1
}

$opacity = 0.95

windowrule {
  name = windowrule-2
  match:class = Alacritty|kitty
  opacity = $opacity $opacity $opacity
}

windowrule {

  name = opacity
  match:class = Alacritty|kitty

  opacity = $opacity, $opacity, $opacity
}

windowrule {
  name = windowrule-3
  match:class = ^steam_app_\d+$
  fullscreen = on
}




# NOTE: Workspaces


windowrule {
  name = windowrule-4
  match:class = ^(?i).*(minecraft|steam|godot|artofrally.x64|org.prismlauncher.PrismLauncher).*$
  workspace = 4 silent
}


windowrule {
  name = windowrule-5
  match:class = discord
  workspace = 7 silent
}


windowrule {
  name = windowrule-6
  match:title = ncspot
  workspace = 9 silent
}

windowrule {
  name = windowrule-7
  match:class = Spotify
  workspace = 9 silent
}


windowrule {
  name = windowrule-8
  match:class = ^ueberzug.*$
  border_size = 0
  no_anim = on
  float = on
  no_focus = on
  no_shadow = on
}



# NOTE: Float rules

# windowrule = float, title:negative:^.*Godot Engine$, class:^.*Godot.*$



windowrule {
  name = prismlauncher
  match:title = Please wait... — Prism Launcher.*
  match:class = org.prismlauncher.PrismLauncher 
  float = on
}

windowrule {
  name = windowrule-9
  match:title = Friends List
  match:class = steam
  float = on
}

windowrule {
  name = windowrule-10
  match:class = nz.co.mega.megasync|scrcpy|org.twosheds.iwgtk|blueman-manager
  float = on
}


windowrule {
  name = windowrule-11
  match:title = float
  float = on
}


windowrule {
  name = windowrule-12
  match:title = ^(Open File)(.*)$
  float = on
}

windowrule {
  name = windowrule-13
  match:title = ^(Select a File)(.*)$
  float = on
}

windowrule {
  name = windowrule-14
  match:title = ^(Choose wallpaper)(.*)$
  float = on
}

windowrule {
  name = windowrule-15
  match:title = ^(Open Folder)(.*)$
  float = on
}

windowrule {
  name = windowrule-16
  match:title = ^(Save As)(.*)$
  float = on
}

windowrule {
  name = windowrule-17
  match:title = ^(Library)(.*)$
  float = on
}

windowrule {
  name = 1
  match:title = ws-1
  workspace = 1 silent
}

windowrule {
  name = 2
  match:title = ws-2
  workspace = 2 silent
}

windowrule {
  name = 3
  match:title = ws-3
  workspace = 3 silent
}

windowrule {
  name = 4
  match:title = ws-4
  workspace = 4 silent
}

windowrule {
  name = 5
  match:title = ws-5
  workspace = 5 silent
}

windowrule {
  name = 6
  match:title = ws-6
  workspace = 6 silent
}

windowrule {
  name = 7
  match:title = ws-7
  workspace = 7 silent
}

windowrule {
  name = 8
  match:title = ws-8
  workspace = 8 silent
}

windowrule {
  name = 9
  match:title = ws-9
  workspace = 9 silent
}

windowrule {
  name = 10
  match:title = ws-0
  workspace = 10 silent
}


windowrule {
  name = tray
  match:class = nz\.co\.mega\.megasync|org\.twosheds\.iwgtk

  float = on
  move = (cursor_x - window_w), cursor_y
}
