use_nerdfont=true
notify=true
flip_status_indicators=true
repeat="playlist"

[keybindings]
"Space" = "playpause"

"Ctrl+l" = "seek +10000"
"L" = "seek +5000"

"Ctrl+h" = "seek -10000"
"H" = "seek -5000"

"Tab" = "move right 1"
"Shift+Tab" = "move left 1"

"Esc" = "back"
"q" = "back"
"g" = "move top"
"G" = "move bottom"


"F1" = "focus library"
"F2" = "focus queue"
"F3" = "focus search"
"F4" = "focus cover"
"Ctrl+k" = "focus search"

"Ctrl+q" = "quit"


[theme]
background = "#1e1e2e"
primary = "#cdd6f4"
secondary = "#94e2d5"
title = "#cba6f7"
playing = "#a6e3a1"
playing_bg = "#2A2B3C"
highlight = "#cdd6f4"
highlight_bg = "#746292"
playing_selected = "#a6e3a1"
error = "#1e1e2e"
error_bg = "#f38ba8"
statusbar = "#cba6f7"
statusbar_bg = "#313244"
statusbar_progress = "#cba6f7"
cmdline = "#cba6f7"
cmdline_bg = "#181825"
