general.import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[env]
TERM = "alacritty"

[font]
size = 9.0

[font.normal]
family = "mononoki Nerd Font"
style = "Regular"

[window.dimensions]
columns = 110
lines = 40

[window.padding]
x = 10
y = 10
